Feat develop more
DTStack/ant-design-testing pull request #2
Opened 2023-09-14 02:27 UTC by JackWang032

- 新组件开发
- 剩余部分query， 代码统一格式化

2023-09-18 06:41 UTC, mortalYoung requested changes

2023-09-18 06:41 UTC, mortalYoung commented on src/alert/index.ts
> +    const selector = `.${prefix}-alert`;
这里直接写 prefix 在项目里倒是没问题，但是在 Taier 里试用的时候我发现会有问题，拿不到 set 过后的值。我理解可能是写外面先执行了，然后再 set。你可以排查一下

2023-10-11 10:47 UTC, JackWang032 commented on src/alert/index.ts
> +    const selector = `.${prefix}-alert`;
是有这个问题，从index.js引入provider，会使各自组件import提升 先执行一遍

2023-10-16 07:53 UTC, mortalYoung requested changes

2023-10-16 07:53 UTC, mortalYoung commented on src/provider/index.ts
> +    prefixCls: 'ant',
默认值改了的话 `tests/setupTests.ts` 这个文件里面相关代码应该就不需要了

2023-10-23 07:25 UTC, mortalYoung approved these changes
+1

2023-10-26 03:07 UTC, merged